### ISSUE TITLE
web-portal can not start after install; unable to open database file

### ISSUE THREAD

**Issue by anders-m** [enchant97/web-portal#92]
Hi enchant97

I used the Compose file installation method in Portainer, but the container will not start. Here are the log, maybe you can see what is going on?:

sqlite3.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.10/site-packages/quart/asgi.py", line 311, in __call__
    await self.app.startup()
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1936, in startup
    await self.ensure_async(func)()
  File "/app/.venv/lib/python3.10/site-packages/tortoise/contrib/quart/__init__.py", line 90, in init_orm
    await Tortoise.generate_schemas()
  File "/app/.venv/lib/python3.10/site-packages/tortoise/__init__.py", line 636, in generate_schemas
    await generate_schema_for_client(connection, safe)
  File "/app/.venv/lib/python3.10/site-packages/tortoise/utils.py", line 31, in generate_schema_for_client
    await generator.generate_from_string(schema)
  File "/app/.venv/lib/python3.10/site-packages/tortoise/backends/base/schema_generator.py", line 448, in generate_from_string
    await self.client.execute_script(creation_string)
  File "/app/.venv/lib/python3.10/site-packages/tortoise/backends/sqlite/client.py", line 36, in translate_exceptions_
    raise OperationalError(exc)
tortoise.exceptions.OperationalError: unable to open database file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/.venv/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 188, in asyncio_worker
      
(
  File "/app/.venv/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 230, in _run
    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/.venv/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 81, in worker_serve
    raise exception
  File "/app/.venv/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py", line 43, in handle_lifespan
    await self.app(
  File "/app/.venv/lib/python3.10/site-packages/hypercorn/app_wrappers.py", line 33, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1902, in __call__
    await self.asgi_app(scope, receive, send)
  File "/app/.venv/lib/python3.10/site-packages/quart/app.py", line 1928, in asgi_app
    await asgi_handler(receive, send)
  File "/app/.venv/lib/python3.10/site-packages/quart/asgi.py", line 313, in __call__
    await send(
  File "/app/.venv/lib/python3.10/site-packages/hypercorn/asyncio/lifespan.py", line 101, in asgi_send
    raise LifespanFailureError("startup", message["message"])
hypercorn.utils.LifespanFailureError: Lifespan failure in startup. 'unable to open database file'

**Comment by enchant97** [comment]
@anders-m there is a mistake in the documentation, the `DB_URI` environment variable will need to be set to: `sqlite:///app/data/db.sqlite`. Also ensure that you have a volume for `/app/data`.

**Comment by anders-m** [comment]
Ahh, I didn't notice that, just copy pasted the text. That did the trick, thanks for your fast reply and your work :-)
